global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: 'proposta_prod'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['proposta:8080']

  - job_name: 'proposta_dev'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']